name = "nas-xero-connector"
main = "worker.js"
compatibility_date = "2024-09-01"

kv_namespaces = [
  { binding = "XERO_KV" }
]

services = [
  { binding = "APP_WORKER", service = "newcastle-automotive-solutions" }
]

[vars]
ALLOWED_ORIGIN = "*"
DEFAULT_ACCOUNT_CODE = "200"
