name = "nas-xero-connector"
main = "worker.js"
compatibility_date = "2024-09-01"

kv_namespaces = [
  { binding = "XERO_KV", id = "{"tenantId":"fe49ed03-ed40-466b-8f29-256133cdd6e0","tenantName":"Newcastle Automotive Solutions","refreshToken":"mt1VfKulzW_jPbg02HSK4BM3Ny7dWN7WpstA987nVKs","connectedAt":1789712851022}" }
]

services = [
  { binding = "APP_WORKER", service = "newcastle-automotive-solutions" }
]

[vars]
ALLOWED_ORIGIN = "*"
DEFAULT_ACCOUNT_CODE = "200"
